### PR TITLE
For now we should ignore libs in other builds too

### PR DESCRIPTION
**Pull request by Coquinho**
This PR deasble every lib that is not evil and eina for every plataform.

### CODE REVIEW

**Comment by JPTIZ** [comment]
Could you explain the reason exactly?

**Comment by Coquinho** [comment]
So we compile on linux

**Comment by cauebs** [comment]
I think it makes sense. We can tackle problems on the linux build as we re-enable libs, one by one. CI will remind us.

**Comment by Coquinho** [comment]
@walac and @JPTIZ convinced me that letting then disabled only at Windows builds would be better as we could be sure our changes didn't break any other thing (when Travis-CI is on).
So I'm closing this.

**Pull request closed without merging**
