### PR TITLE
ecore: Correct unneeded underscore

### PR DESCRIPTION
**Pull request by Coquinho**

### CODE REVIEW

**Comment by felipealmeida** [comment]
vocês estão colocando guards cegamente? Pois framebuffer não é compilado no Windows...

**Comment by Coquinho** [comment]
> vocês estão colocando guards cegamente? Pois framebuffer não é compilado no Windows...

A [CI](https://github.com/expertisesolutions/efl/runs/855493081#step:23:4281) apontou erro, então eu coloquei guard

**Comment by felipealmeida** [comment]
tem algo errado, não tem como compilar ecore_test_fb

**Comment by Coquinho** [comment]
> tem algo errado, não tem como compilar ecore_test_fb

como assim, não tem como?

**Comment by Coquinho** [comment]
`fb` is disabled by default so how is it compiling here? No idea! so moving this to draft.

**Comment by Coquinho** [comment]
Ok....So I rebased it with `native-windows` again, and somehow now it [works](https://github.com/expertisesolutions/efl/runs/858814561)... So I presume this error was a bad conflict resolution that I've done. Closing this.

**Comment by joaoantoniocardoso** [comment]
> Ok....So I rebased it with `native-windows` again, and somehow now it [works](https://github.com/expertisesolutions/efl/runs/858814561)... So I presume this error was a bad conflict resolution that I've done. Closing this.

wait, [this](https://github.com/expertisesolutions/efl/blob/84c2e125dffd8cda779ae6119c00ea21105df2e3/src/tests/ecore/ecore_test_ecore.c#L7) need to be fixed.

**Comment by Coquinho** [comment]
> > Ok....So I rebased it with `native-windows` again, and somehow now it [works](https://github.com/expertisesolutions/efl/runs/858814561)... So I presume this error was a bad conflict resolution that I've done. Closing this.
> 
> wait, [this](https://github.com/expertisesolutions/efl/blob/84c2e125dffd8cda779ae6119c00ea21105df2e3/src/tests/ecore/ecore_test_ecore.c#L7) needs to be fixed.


You are right, my bad.

**Pull request merged**
