### PR TITLE
ci: Install lua in github actions

### PR DESCRIPTION
**Pull request by JPTIZ**
Needed for #149

### CODE REVIEW

**Comment by joaoantoniocardoso** [comment]
Also needed for #140.

**Comment by Coquinho** [comment]
Is this still needed?

**Comment by JPTIZ** [comment]
> 
> 
> Is this still needed?

Nah. But still #307 is not merged yet, so...

**Comment by Coquinho** [comment]
> > Is this still needed?
> 
> Nah. But still #307 is not merged yet, so...

There is a lua/luajit wrap at native-windows already. I don't understand the point of maintaining this.

**Comment by JPTIZ** [comment]
> There is a lua/luajit wrap at native-windows already. I don't understand the point of maintaining this.

Well remembered, you have a point.

**Pull request closed without merging**
