### PR TITLE
Devs/felipealmeida/native windows/ecore api

### PR DESCRIPTION
**Pull request by felipealmeida**

### CODE REVIEW

**Comment by joaoantoniocardoso** [comment]
I have some doubts here:
- Why the symbols `EWAPI` and `EOAPI` from `src/tests/ecore` was changed to `EAPI EAPI_WEAK` and these same symbols from `src/libs/ecore` was changed to `ECORE_API ECORE_API_WEAK`?
- The symbol `ECORE_STATIC` shouldn't be defined in meson.build, like `ECORE_BUILD`?

**Comment by JPTIZ** [comment]
> I have some doubts here:
> 
>     * Why the symbols `EWAPI` and `EOAPI` from `src/tests/ecore` was changed to `EAPI EAPI_WEAK` and these same symbols from `src/libs/ecore` was changed to `ECORE_API ECORE_API_WEAK`?

Good point. Probably both should be `ECORE_API ECORE_API_WEAK`.

>     * The symbol `ECORE_STATIC` shouldn't be defined in meson.build, like `ECORE_BUILD`?

`ECORE_STATIC` is probably going to be dropped actually, since static linking for EFL will be dropped.

**Comment by Coquinho** [comment]
May we close this? #175 + #171 seems to do this.

**Comment by walac** [comment]
> May we close this? #175 + #171 seems to do this.

 Closing

**Pull request closed without merging**
