### PR TITLE
eina_api.h is no longer necessary

### PR DESCRIPTION
**Pull request by joaoantoniocardoso**
EINA_API is now defined in `src/lib/eina/eina_types.h` and `src/lib/eina/eina_api.h` is no longer necessary.

### CODE REVIEW

**Comment by Coquinho** [comment]
This may need a rebase now.

**Comment by Coquinho** [comment]
@felipealmeida maybe it would be a good idea to add this change to [D11993](https://phab.enlightenment.org/D11993)?

**Comment by joaoantoniocardoso** [comment]
> @felipealmeida maybe it would be a good idea to add this change to [D11993](https://phab.enlightenment.org/D11993)?

eina_api.h doesn't exist in the upstream: [check here](https://github.com/Enlightenment/efl/blob/master/src/lib/eina/eina_api.h)

**Comment by felipealmeida** [comment]
> 
> 
> @felipealmeida maybe it would be a good idea to add this change to [D11993](https://phab.enlightenment.org/D11993)?

Com certeza. Eu percebi que esse arquivo ainda existia ontem

**Comment by JPTIZ** [comment]
> @felipealmeida maybe it would be a good idea to add this change to [D11993](https://phab.enlightenment.org/D11993)?

But...the file doesn't even exists on that diff.

**Pull request merged**
