### PR TITLE
Fixing ecore_x linkage to elementary examples

### PR DESCRIPTION
**Pull request by joaoantoniocardoso**
Yes, its odd but Elementary should be included first or Ecore_X won't link on linux.

### CODE REVIEW

**Comment by Coquinho** [comment]
If we are going to explicitly include ecore_x I would prefer #144, As it only adds ecore_x when needed.

**Comment by joaoantoniocardoso** [comment]
> If we are going to explicitly include ecore_x I would prefer #144, As it only adds ecore_x when needed.

I completely forgot that PR and... Ok, I also prefer #144.

> Oh it is that thing again. The weird part: `ecore_x` is already a dependency of `elementary`...but somehow it just blows up for no reason.

welp, where is it declared?

**Comment by Coquinho** [comment]
> > If we are going to explicitly include ecore_x I would prefer #144, As it only adds ecore_x when needed.
> 
> I completely forgot that PR and... Ok, I also prefer #144.
> 
> > Oh it is that thing again. The weird part: `ecore_x` is already a dependency of `elementary`...but somehow it just blows up for no reason.
> 
> welp, where is it declared?

It is declared at elementary's [meson.build](https://github.com/expertisesolutions/efl/blob/0132b75586fed26f80f9c469390565b797d46cc5/src/lib/elementary/meson.build#L990)

**Comment by Coquinho** [comment]
> Oh it is that thing again. The weird part: `ecore_x` is already a dependency of `elementary`...but somehow it just blows up for no reason.

And the best part, somehow it doesn't blow at masters

**Comment by Coquinho** [comment]
> > If we are going to explicitly include ecore_x I would prefer #144, As it only adds ecore_x when needed.
> 
> I completely forgot that PR and... Ok, I also prefer #144.

@joaoantoniocardoso so I will make It ready.

**Comment by joaoantoniocardoso** [comment]
> > > If we are going to explicitly include ecore_x I would prefer #144, As it only adds ecore_x when needed.
> > 
> > 
> > I completely forgot that PR and... Ok, I also prefer #144.
> 
> @joaoantoniocardoso so I will make It ready.

Closing this one in favor of #144.

**Comment by JPTIZ** [comment]
Suppressed by #144.

**Pull request closed without merging**
