### PR TITLE
build: Fix libjpeg trying to link with freetype

### PR DESCRIPTION
**Pull request by JPTIZ**

### CODE REVIEW

**Comment by Coquinho** [comment]
Is this PR ready for review? Its kind confuse when the title says "try"

**Comment by JPTIZ** [comment]
> Is this PR ready for review? Its kind confuse when the title says "try"

Yes, it is. The meaning is "libjpeg currently tries to link with freetype. This patches fixes it by making it link to the right one"

**Comment by Coquinho** [comment]
oh okay

**Comment by Coquinho** [comment]
How can we see if ilbjpeg is being imported correctly?

**Comment by JPTIZ** [comment]
> How can we see if ilbjpeg is being imported correctly?

I think this will have to be done locally with `-Dnuget-download=true`. Also, shouldn't we have a CI target with this? (And another without)

**Comment by Coquinho** [comment]
> > How can we see if ilbjpeg is being imported correctly?
> 
> I think this will have to be done locally with `-Dnuget-download=true`. Also, shouldn't we have a CI target with this? (And another without)

Don't know, how could this work?

**Comment by JPTIZ** [comment]
> > > How can we see if ilbjpeg is being imported correctly?
> > 
> > 
> > I think this will have to be done locally with `-Dnuget-download=true`. Also, shouldn't we have a CI target with this? (And another without)
> 
> Don't know, how could this work?

Just make a clone of the current Windows pipeline, but adding the flag.

**Comment by joaoantoniocardoso** [comment]
@JPTIZ  Did you noticed that this is being fixed [here](https://github.com/expertisesolutions/efl/pull/250/files) too?

**Comment by JPTIZ** [comment]
> @JPTIZ Did you noticed that this is being fixed [here](https://github.com/expertisesolutions/efl/pull/250/files) too?

_Shhhhh!_

**Comment by Coquinho** [comment]
So this will be closed?

**Pull request closed without merging**
