### PR TITLE
build: Fallback libjpeg to wrap

### PR DESCRIPTION
**Pull request by JPTIZ**
Needs a meson with https://github.com/mesonbuild/meson/pull/7381.

### CODE REVIEW

**Comment by Coquinho** [comment]
Do you know in which version this was added?

**Comment by Coquinho** [comment]
Have you tested if this patch doesn't break master?

**Comment by JPTIZ** [comment]
> Have you tested if this patch doesn't break master?

I can't: I can't isolate `jpeg` (uninstall it or whatever) heh.



> Do you know in which version this was added?

Apparently 0.55.

**Comment by Coquinho** [comment]
> > Have you tested if this patch doesn't break master?
> 
> I can't: I can't isolate `jpeg` (uninstall it or whatever) heh.

ohhh, so how can we test this?

> > Do you know in which version this was added?
> 
> Apparently 0.55.

Oh nice, so we can work with it without changes

**Comment by JPTIZ** [comment]
Since 0.55 isn't out yet, I'm letting this as a draft.

**Comment by Coquinho** [comment]
oh, I thought ours was 0.55 :(
It is [54.3](https://github.com/expertisesolutions/efl/pull/202/checks?check_run_id=823958499#step:14:4) :(

**Comment by Coquinho** [comment]
Is this still needed? #291  doesn't cover it?

**Comment by JPTIZ** [comment]
> 
> 
> Is this still needed? #291 doesn't cover it?

#291 is _using_ this one :D

**Comment by Coquinho** [comment]
> > Is this still needed? #291 doesn't cover it?
> 
> #291 is _using_ this one :D

Yeah, but it has all the commits, making this unnecessary. Unless #291 should depend on this one.

**Comment by joaoantoniocardoso** [comment]
> > > Is this still needed? #291 doesn't cover it?
> > 
> > 
> > #291 is _using_ this one :D
> 
> Yeah, but it has all the commits, making this unnecessary. Unless #291 should depend on this one.

If the other PR is merged then this PR will no longer be necessary, so we should wait.

**Comment by Coquinho** [comment]
> > > > Is this still needed? #291 doesn't cover it?
> > > 
> > > 
> > > #291 is _using_ this one :D
> > 
> > 
> > Yeah, but it has all the commits, making this unnecessary. Unless #291 should depend on this one.
> 
> If the other PR is merged then this PR will no longer be necessary, so we should wait.

Is there any reason to choose this one over #291?

**Comment by JPTIZ** [comment]
> 
> 
> > > > > Is this still needed? #291 doesn't cover it?
> > > > 
> > > > 
> > > > #291 is _using_ this one :D
> > > 
> > > 
> > > Yeah, but it has all the commits, making this unnecessary. Unless #291 should depend on this one.
> > 
> > 
> > If the other PR is merged then this PR will no longer be necessary, so we should wait.
> 
> Is there any reason to choose this one over #291?

It is *just* the libjpeg wrap, not a bunch of everything.

Also, @joaoantoniocardoso is libjpeg linking properly for you?

**Comment by joaoantoniocardoso** [comment]
> > > > > > Is this still needed? #291 doesn't cover it?
> > > > > 
> > > > > 
> > > > > #291 is _using_ this one :D
> > > > 
> > > > 
> > > > Yeah, but it has all the commits, making this unnecessary. Unless #291 should depend on this one.
> > > 
> > > 
> > > If the other PR is merged then this PR will no longer be necessary, so we should wait.
> > 
> > 
> > Is there any reason to choose this one over #291?
> 
> It is _just_ the libjpeg wrap, not a bunch of everything. So if we resolve this before, it can be merged faster.
> Also, @joaoantoniocardoso is libjpeg linking properly for you?

On the other PR, yes. You can see the use case in #332.

**Comment by JPTIZ** [comment]
> 
> 
> > > > > > > Is this still needed? #291 doesn't cover it?
> > > > > > 
> > > > > > 
> > > > > > #291 is _using_ this one :D
> > > > > 
> > > > > 
> > > > > Yeah, but it has all the commits, making this unnecessary. Unless #291 should depend on this one.
> > > > 
> > > > 
> > > > If the other PR is merged then this PR will no longer be necessary, so we should wait.
> > > 
> > > 
> > > Is there any reason to choose this one over #291?
> > 
> > 
> > It is _just_ the libjpeg wrap, not a bunch of everything. So if we resolve this before, it can be merged faster.
> > Also, @joaoantoniocardoso is libjpeg linking properly for you?
> 
> On the other PR, yes. You can see the use case in #332.

Oh I see, you're using **our** libjpeg, hm...let me try that.

**Comment by JPTIZ** [comment]
Wow it works.

Ready for review.

**Pull request merged**
