### PR TITLE
Disabling evil when compiling for linux

### PR DESCRIPTION
**Pull request by joaoantoniocardoso**

### CODE REVIEW

**Comment by Coquinho** [comment]
> This shouldn't be done. `evil` is already "ignored" in `src/lib/evil/meson.build`. Mind explaining the issue?

oh you are right, evil's meson.build is guarded with `if target_machine.system() == 'windows'
`

**Comment by Coquinho** [comment]
Oh, probably what he intended to do is somehow disable evils tests while compiling at Linux, I got this error too.

**Comment by JPTIZ** [comment]
> Oh, probably what he intended to do is somehow disable evils tests while compiling at Linux, I got this error too.

But what error? ;-;

**Comment by JPTIZ** [comment]
Ok, @Coquinho told me that sometimes `evil_private.h` will be included and thus not found. If that's the case, check if `evil_private.h` is surrounded with `#ifndef _WIN32`.

**Comment by JPTIZ** [comment]
Except when you end up building tests - ok, my bad in not seeing this scenario. In this case, surround src/tests/evil/meson.build's code with `if sys_windows`:

```diff
diff --git a/src/tests/evil/meson.build b/src/tests/evil/meson.build
index 57d1899eb2..0c4cfdc0e5 100644
--- a/src/tests/evil/meson.build
+++ b/src/tests/evil/meson.build
@@ -1,24 +1,26 @@
-evil_test_src = files(
-'evil_suite.c',
-'evil_suite.h',
-'evil_test_dlfcn.c',
-'evil_test_main.c',
-'evil_test_stdio.c',
-'evil_test_stdlib.c',
-'evil_test_unistd.c',
-)
+if sys_windows
+  evil_test_src = files(
+  'evil_suite.c',
+  'evil_suite.h',
+  'evil_test_dlfcn.c',
+  'evil_test_main.c',
+  'evil_test_stdio.c',
+  'evil_test_stdlib.c',
+  'evil_test_unistd.c',
+  )

-evil_test_exe = executable('evil_suite',
-  include_directories : config_dir,
-  sources : evil_test_src,
-  dependencies: [m, check, eina, evil],
-  c_args : [
-  '-DTESTS_WD="`pwd`"',
-  '-DTESTS_BUILD_DIR="'+meson.current_build_dir()+'"',
-  '-DTESTS_SRC_DIR="'+meson.current_source_dir()+'"']
-)
+  evil_test_exe = executable('evil_suite',
+    include_directories : config_dir,
+    sources : evil_test_src,
+    dependencies: [m, check, eina, evil],
+    c_args : [
+    '-DTESTS_WD="`pwd`"',
+    '-DTESTS_BUILD_DIR="'+meson.current_build_dir()+'"',
+    '-DTESTS_SRC_DIR="'+meson.current_source_dir()+'"']
+  )

-test('evil', evil_test_exe,
-  env : test_env,
-  timeout : 60,
-)
+  test('evil', evil_test_exe,
+    env : test_env,
+    timeout : 60,
+  )
+endif
```

**Comment by joaoantoniocardoso** [comment]
@JPTIZ thanks, this little change makes much more sense

**Pull request merged**
