### PR TITLE
Linux Build: Use Eina_Lock instead of pthread_mutex_t

### PR DESCRIPTION
**Pull request by Coquinho**
`_eina_tracking_lock` was been seted as diferents types at `eina_main.c`
and `eina_inline_lock_posix.x` causing:
```
   ../src/lib/eina/eina_main.c:113:20: error: conflicting types for '_eina_tracking_lock'
     113 | EINA_API Eina_Lock _eina_tracking_lock;
         |                    ^~~~~~~~~~~~~~~~~~~
   In file included from ../src/lib/eina/eina_lock.h:103,
                    from ../src/lib/eina/eina_main.c:43:
   ../src/lib/eina/eina_inline_lock_posix.x:155:33: note: previous declaration of '_eina_tracking_lock' was here
     155 | EINA_API extern pthread_mutex_t _eina_tracking_lock;
         |                                 ^~~~~~~~~~~~~~~~~~~
```
~Depends on #111~

### CODE REVIEW

**Comment by Coquinho** [comment]
Moving it to a draft as it yields things like:
```
../src/lib/eina/eina_inline_lock_posix.x:238:30: warning: passing argument 1 of 'pthread_mutex_unlock' from incompatible pointer type [-Wincompatible-pointer-types]
  238 |         pthread_mutex_unlock(&_eina_tracking_lock);
      |                              ^~~~~~~~~~~~~~~~~~~~
      |                              |
      |                              Eina_Lock * {aka struct _Eina_Lock *}
```
You can have a look at [trevis-ci](https://travis-ci.com/github/Coquinho/efl/jobs/343584344)

**Comment by walac** [comment]
Shouldn't we move all `pthread_mutex_lock` to `eina_thread_lock`.

**Comment by Coquinho** [comment]
> Shouldn't we move all `pthread_mutex_lock` to `eina_thread_lock`.

@walac should we do the same at windows functions?
If so, I will work on 2 PR one for each architecture.

**Comment by walac** [comment]
>  should we do the same at windows functions?

@Coquinho I believe so. Can you point me at the specific code?

**Comment by Coquinho** [comment]
It happens at the same locations as in the posix version, so you may search for `_eina_tracking_lock`

**Comment by Coquinho** [comment]
This PR has been rebased to `native-windows`.
@walac you requested changes, are they to your suit?

**Pull request merged**
